namespace Soti.MobiControl.WindowsModern.Models
{
    public sealed class WindowsLocalUserNameAndPasswordModel
    {
        /// <summary>
        /// Gets or sets User Name.
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets Local User Auto Generated Password.
        /// </summary>
        public string AutoGeneratedPassword { get; set; }
    }
}
