using System;
using System.Collections.Generic;

namespace Soti.MobiControl.WindowsModern.Models
{
    /// <summary>
    /// Windows device local user model.
    /// </summary>
    public sealed class WindowsDeviceLocalUserModel
    {
        /// <summary>
        /// Gets or sets LocalUserId.
        /// </summary>
        public int WindowsDeviceLocalUserId { get; set; }

        /// <summary>
        /// Gets or sets SID.
        /// </summary>
        public string SID { get; set; }

        /// <summary>
        /// Gets or sets User Name.
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets UserGroups.
        /// </summary>
        public IEnumerable<string> UserGroups { get; set; }

        /// <summary>
        /// Gets or sets DeviceId.
        /// </summary>
        public int DeviceId { get; set; }

        /// <summary>
        /// Gets or sets IsMobiControlCreated.
        /// </summary>
        public bool IsMobiControlCreated { get; set; }

        /// <summary>
        /// Gets or sets Local User Auto Generated Password.
        /// </summary>
        public string AutoGeneratedPassword { get; set; }

        /// <summary>
        /// Gets or sets ReferenceID.
        /// </summary>
        public DateTime? CreatedDate { get; set; }
    }
}