using System;
using System.Collections.Generic;
using Soti.MobiControl.WindowsModern.Implementation.Models;
using Soti.MobiControl.WindowsModern.Models;

namespace Soti.MobiControl.WindowsModern.Implementation.Converters;

internal static class DeviceLocalUserDataConverter
{
    public static WindowsDeviceLocalUserModel ToDeviceLocalUsersModel(this WindowsDeviceUserData localUserData, string decryptedPassword, IEnumerable<string> userGroups)
    {
        if (localUserData == null)
        {
            throw new ArgumentNullException(nameof(localUserData));
        }

        return new WindowsDeviceLocalUserModel
        {
            WindowsDeviceLocalUserId = localUserData.WindowsDeviceUserId,
            SID = localUserData.UserSID,
            UserName = localUserData.UserName,
            UserGroups = userGroups,
            DeviceId = localUserData.DeviceId,
            IsMobiControlCreated = localUserData.IsMobiControlCreated,
            AutoGeneratedPassword = decryptedPassword,
            CreatedDate = localUserData.CreatedDate
        };
    }

    public static DeviceLocalUserSummary ToDeviceLocalUsersBasicModel(this WindowsDeviceUserData localUserData, IEnumerable<string> userGroups)
    {
        if (localUserData == null)
        {
            throw new ArgumentNullException(nameof(localUserData));
        }

        return new DeviceLocalUserSummary
        {
            Sid = localUserData.UserSID,
            UserName = localUserData.UserName,
            UserGroups = userGroups,
            IsMobiControlCreated = localUserData.IsMobiControlCreated
        };
    }

    public static WindowsDeviceLocalUserModel ToDeviceLocalUsersBasicModel(this WindowsDeviceUserData localUserData)
    {
        if (localUserData == null)
        {
            throw new ArgumentNullException(nameof(localUserData));
        }

        return new WindowsDeviceLocalUserModel
        {
            WindowsDeviceLocalUserId = localUserData.WindowsDeviceUserId,
            UserGroups = localUserData.UserGroups,
            DeviceId = localUserData.DeviceId
        };
    }

    public static WindowsDeviceUserData ToWindowsDeviceUserData(this WindowsDeviceLocalUserModel localUser, byte[] password, int dataKeyId)
    {
        if (localUser == null)
        {
            throw new ArgumentNullException(nameof(localUser));
        }

        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = localUser.WindowsDeviceLocalUserId,
            UserSID = localUser.SID,
            UserName = localUser.UserName,
            UserGroups = null,
            DeviceId = localUser.DeviceId,
            IsMobiControlCreated = localUser.IsMobiControlCreated,
            AutoGeneratedPassword = password,
            CreatedDate = localUser.CreatedDate,
            DataKeyId = dataKeyId
        };
    }
}
