namespace Soti.MobiControl.WindowsModern.Web.Contracts
{
    public sealed class DeviceLocalUserPassword
    {
        /// <summary>
        /// Gets or sets the auto generated password.
        /// </summary>
        public string AutoGeneratedPassword { get; set; }
    }
}
