//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soti.MobiControl.WindowsModern.Web.Implementation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soti.MobiControl.WindowsModern.Web.Implementation.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Count.
        /// </summary>
        internal static string lbl_device_group_peripheral_property_deviceCount {
            get {
                return ResourceManager.GetString("lbl_device_group_peripheral_property_deviceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Manufacturer.
        /// </summary>
        internal static string lbl_device_group_peripheral_property_manufacturer {
            get {
                return ResourceManager.GetString("lbl_device_group_peripheral_property_manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Name.
        /// </summary>
        internal static string lbl_device_group_peripheral_property_name {
            get {
                return ResourceManager.GetString("lbl_device_group_peripheral_property_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Type.
        /// </summary>
        internal static string lbl_device_group_peripheral_property_peripheralType {
            get {
                return ResourceManager.GetString("lbl_device_group_peripheral_property_peripheralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Status.
        /// </summary>
        internal static string lbl_device_group_peripheral_property_status {
            get {
                return ResourceManager.GetString("lbl_device_group_peripheral_property_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Version.
        /// </summary>
        internal static string lbl_device_group_peripheral_property_version {
            get {
                return ResourceManager.GetString("lbl_device_group_peripheral_property_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Detections Till Date.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_currentdetectioncount {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_currentdetectioncount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_deviceid {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_deviceid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_devid {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_devid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Id.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_externalthreatid {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_externalthreatid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Detection Time.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_initialdetectiontime {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_initialdetectiontime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Scanned Time.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_lastscandate {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_lastscandate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Status Change Time.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_laststatuschangetime {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_laststatuschangetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Status.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_lastthreatstatus {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_lastthreatstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Devices.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_numberofdevices {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_numberofdevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_severity {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_threatcategory {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_threatcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Name.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_threatname {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_threatname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Status.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_threatstatus {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_threatstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Category.
        /// </summary>
        internal static string lbl_windows_modern_defender_property_type {
            get {
                return ResourceManager.GetString("lbl_windows_modern_defender_property_type", resourceCulture);
            }
        }
    }
}
