using Soti.Data.SqlClient;
using Soti.Diagnostics;
using Soti.MobiControl.WindowsModern.Implementation.Models;
using Soti.MobiControl.WindowsModern.Models;
using Soti.MobiControl.WindowsModern.Models.Enums;
using Soti.Utilities.Collections;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;

namespace Soti.MobiControl.WindowsModern.Implementation.Providers.Ado;

internal sealed class WindowsDeviceUserProvider : IWindowsDeviceUserProvider
{
    private const string DeviceId = "DeviceId";
    private const string DeviceIds = "DeviceIds";
    private const string Id = "Id";
    private const string WindowsDeviceUserId = "WindowsDeviceUserId";
    private const string UserSId = "UserSID";
    private const string UserSids = "UserSIDs";
    private const string UserName = "UserName";
    private const string UserGroups = "UserGroups";
    private const string DeviceIdHasValue = "DeviceIdHasValue";
    private const string UserSIdHasValue = "UserSIDHasValue";
    private const string UserGroupsHasValue = "UserGroupsHasValue";
    private const string IsMobiControlCreatedHasValue = "IsMobiControlCreatedHasValue";
    private const string AutoGeneratedPasswordHasValue = "AutoGeneratedPasswordHasValue";
    private const string DataKeyIdHasValue = "DataKeyIdHasValue";
    private const string UserNameHasValue = "UserNameHasValue";
    private const string IsMobiControlCreated = "IsMobiControlCreated";
    private const string AutoGeneratedPassword = "AutoGeneratedPassword";
    private const string DataKeyId = "DataKeyId";
    private const string CreatedDate = "CreatedDate";
    private const string Records = "Records";
    private const string WindowsDeviceUsers = "WindowsDeviceUsers";
    private const string UserFullName = "UserFullName";
    private const string UserDomain = "UserDomain";
    private const string WindowsDeviceUserType = "WindowsDeviceUserType";
    private const string LastCheckInDeviceUserTime = "LastCheckInDeviceUserTime";
    private const string LogName = "WindowsLocalUserPassword";

    private readonly IProgramTrace _programTrace;
    private readonly IDatabase _database;

    /// <summary>
    /// Initializes a new instance of the <see cref="WindowsDeviceUserProvider"/> class.
    /// </summary>
    /// <param name="database">the instance of IDatabase.</param>
    /// <param name="programTrace"></param>
    public WindowsDeviceUserProvider(IDatabase database, IProgramTrace programTrace)
    {
        _programTrace = programTrace ?? throw new ArgumentNullException(nameof(programTrace));
        _database = database ?? throw new ArgumentNullException(nameof(database));
    }

    /// <inheritdoc/>
    public IReadOnlyList<WindowsDeviceUserData> GetAllLocalUsersDataByDeviceId(int deviceId)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetByFK_DeviceId"];

        command.Parameters.Add(DeviceId, deviceId);

        return command.ExecuteReader((x) => ReadCollection(x, deviceId));
    }

    /// <inheritdoc/>
    public IReadOnlyList<WindowsDeviceUserData> GetAllLocalUsersData()
    {
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetAllDeviceIdAndUserGroups"];
        return command.ExecuteReader(ReadLocalUserCollection);
    }

    /// <inheritdoc/>
    public IReadOnlyList<WindowsDeviceUserData> GetAllLocalUsersBasicDataByDeviceId(int deviceId)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetBasicBy_DeviceId"];

        command.Parameters.Add(DeviceId, deviceId);

        return command.ExecuteReader((x) => ReadBasicCollection(x));
    }

    /// <inheritdoc/>
    public WindowsDeviceUserData GetLocalUsersDataByDeviceIdAndSid(int deviceId, string userSid)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        if (string.IsNullOrWhiteSpace(userSid))
        {
            throw new ArgumentException("Parameter cannot be null or empty", nameof(userSid));
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetByIndex_DeviceIdUserSID"];

        command.Parameters.Add(DeviceId, deviceId);
        command.Parameters.Add(UserSId, userSid);

        return command.ExecuteReader((x) => ReadCollection(x, deviceId, userSid)).FirstOrDefault();
    }

    /// <inheritdoc />
    public IReadOnlyList<WindowsDeviceLocalUserModel> GetLocalUserNamesByDeviceIdAndSids(int deviceId, IEnumerable<string> userSids)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        var userSidsList = userSids.AsArray();
        if (userSidsList.Count == 0)
        {
            return new List<WindowsDeviceLocalUserModel>();
        }

        var dataTable = new DataTable("GEN_UDT_NVarcharIdentifier256") { Locale = CultureInfo.InvariantCulture };
        dataTable.Columns.Add(new DataColumn(Id, typeof(string)) { AllowDBNull = false });
        foreach (var userSid in userSidsList)
        {
            dataTable.Rows.Add(userSid);
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetUserName_ByDeviceIdAndUserSIDs"];
        command.Parameters.Add(DeviceId, deviceId);
        command.Parameters.Add(UserSids, dataTable, SqlDbType.Structured);

        return command.ExecuteReader(ReadLocalUserNamesList);
    }

    public WindowsDeviceUserData GetLocalUsersPasswordByDeviceIdAndSid(int deviceId, string userSid)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        if (string.IsNullOrWhiteSpace(userSid))
        {
            throw new ArgumentException("Parameter cannot be null or empty", nameof(userSid));
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetAutoGeneratedPasswordBy_DeviceIdUserSID"];

        command.Parameters.Add(DeviceId, deviceId);
        command.Parameters.Add(UserSId, userSid);

        return command.ExecuteReader(ReadLocalUserPasswordDetails).FirstOrDefault();
    }

    /// <inheritdoc/>
    public void Delete(int windowsDeviceUserId)
    {
        if (windowsDeviceUserId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(windowsDeviceUserId));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: Delete");
        var command = _database.StoredProcedures["dbo.GEN_WindowsDeviceUser_Delete"];

        command.Parameters.Add(WindowsDeviceUserId, windowsDeviceUserId);

        command.ExecuteNonQuery();
    }

    /// <inheritdoc/>
    public void Insert(WindowsDeviceUserData value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: Insert");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_Insert"];

        command.Parameters.Add(DeviceId, value.DeviceId);
        command.Parameters.Add(UserSId, value.UserSID);
        command.Parameters.Add(UserName, value.UserName);
        command.Parameters.Add(UserGroups, (string)null);
        command.Parameters.Add(IsMobiControlCreated, value.IsMobiControlCreated);
        command.Parameters.Add(AutoGeneratedPassword, value.AutoGeneratedPassword);
        command.Parameters.Add(DataKeyId, value.DataKeyId);
        command.Parameters.Add(CreatedDate, value.CreatedDate);
        command.Parameters.Add(WindowsDeviceUserId, out Ref<int> windowsDeviceUserId);
        command.ExecuteNonQuery();
        value.WindowsDeviceUserId = windowsDeviceUserId;
    }

    /// <inheritdoc/>
    public void Update(WindowsDeviceUserData windowsDeviceUserData)
    {
        if (windowsDeviceUserData == null)
        {
            throw new ArgumentNullException(nameof(windowsDeviceUserData));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: Update");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_Update"];

        command.Parameters.Add(WindowsDeviceUserId, windowsDeviceUserData.WindowsDeviceUserId);
        command.Parameters.Add(DeviceId, windowsDeviceUserData.DeviceId);
        command.Parameters.Add(DeviceIdHasValue, 1);
        command.Parameters.Add(UserSId, windowsDeviceUserData.UserSID);
        command.Parameters.Add(UserSIdHasValue, 1);
        command.Parameters.Add(UserName, windowsDeviceUserData.UserName);
        command.Parameters.Add(UserNameHasValue, 1);
        command.Parameters.Add(UserGroups, (string)null);
        command.Parameters.Add(UserGroupsHasValue, 0);
        command.Parameters.Add(IsMobiControlCreated, windowsDeviceUserData.IsMobiControlCreated);
        command.Parameters.Add(IsMobiControlCreatedHasValue, 1);
        command.Parameters.Add(AutoGeneratedPassword, windowsDeviceUserData.AutoGeneratedPassword);
        command.Parameters.Add(AutoGeneratedPasswordHasValue, 1);
        command.Parameters.Add(DataKeyId, windowsDeviceUserData.DataKeyId);
        command.Parameters.Add(DataKeyIdHasValue, 1);

        command.ExecuteNonQuery();
    }

    /// <inheritdoc />
    public IDictionary<string, int> BulkReplace(int deviceId, IEnumerable<WindowsDeviceUserData> windowsDeviceUserData)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        var windowsDeviceUserDataList = windowsDeviceUserData.AsArray();

        if (windowsDeviceUserDataList.Count == 0)
        {
            throw new ArgumentNullException(nameof(windowsDeviceUserData));
        }

        var localUserOutput = new Dictionary<string, int>();
        var dataTable = CreateDataTable_Bulk_Modify(windowsDeviceUserDataList);

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: BulkReplace");
        var command = _database.StoredProcedures["[dbo].[WindowsDeviceUser_BulkModify_ByDeviceIdAndUserSID]"];
        command.Parameters.Add(Records, dataTable, SqlDbType.Structured);
        command.Parameters.Add(DeviceId, deviceId);
        command.ExecuteReader(reader =>
        {
            while (reader.Read())
            {
                // Stored Procedure returns (WindowsDeviceUserId, UserSID)
                localUserOutput.Add(reader.GetString(1), reader.GetInt32(0));
            }
        });
        return localUserOutput;
    }

    /// <inheritdoc />
    public IDictionary<string, int> BulkUpdate(IEnumerable<WindowsDeviceUserData> windowsDeviceUserData)
    {
        var windowsDeviceUserDataList = windowsDeviceUserData.AsArray();

        if (windowsDeviceUserDataList.Count == 0)
        {
            throw new ArgumentNullException(nameof(windowsDeviceUserData));
        }

        var windowsDeviceUserDataArray = windowsDeviceUserData as WindowsDeviceUserData[] ?? [.. windowsDeviceUserDataList];
        if (windowsDeviceUserDataArray.Any(u => u == null) || !windowsDeviceUserDataArray.Any())
        {
            throw new ArgumentException(nameof(windowsDeviceUserDataList));
        }

        var result = new Dictionary<string, int>();
        var dataTable = CreateDataTable_Bulk_Modify(windowsDeviceUserDataArray);
        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: BulkUpdate");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_BulkModify_ByUC"];
        command.Parameters.Add(WindowsDeviceUsers, dataTable, SqlDbType.Structured);

        command.ExecuteReader(reader =>
        {
            while (reader.Read())
            {
                // Stored Procedure returns (WindowsDeviceUserId, UserSID)
                result.Add(reader.GetString(1), reader.GetInt32(0));
            }
        });
        return result;
    }

    /// <inheritdoc />
    public void DeleteByDeviceId(int deviceId, WindowsDeviceUserType? windowsDeviceUserType = null)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: DeleteByDeviceId {deviceId} ");
        var command = _database.StoredProcedures["[dbo].[WindowsDeviceUser_Delete_ByDeviceIdAndWindowsDeviceUserType]"];
        command.Parameters.Add(DeviceId, deviceId);
        if (windowsDeviceUserType != null)
        {
            command.Parameters.Add(WindowsDeviceUserType, (int)windowsDeviceUserType);
        }

        command.ExecuteNonQuery();
    }

    /// <inheritdoc />
    public void DeleteByUserSid(string userSid, int deviceId)
    {
        if (string.IsNullOrWhiteSpace(userSid))
        {
            throw new ArgumentNullException(nameof(userSid));
        }

        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: DeleteByUserSid {userSid}");
        var command = _database.StoredProcedures["[dbo].[WindowsDeviceUser_Delete_ByDeviceIdAndUserSID]"];
        command.Parameters.Add(UserSId, userSid);
        command.Parameters.Add(DeviceId, deviceId);
        command.ExecuteNonQuery();
    }

    public void ResetPassword(int windowsDeviceUserId)
    {
        if (windowsDeviceUserId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(windowsDeviceUserId));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: ResetPassword {windowsDeviceUserId}");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_Update"];
        command.Parameters.Add(WindowsDeviceUserId, windowsDeviceUserId);
        command.Parameters.Add(AutoGeneratedPasswordHasValue, 1);

        command.ExecuteNonQuery();
    }

    /// <inheritdoc />
    public void ModifyLoggedInUser(WindowsDeviceUserData windowsDeviceUserData)
    {
        if (windowsDeviceUserData == null)
        {
            throw new ArgumentNullException(nameof(windowsDeviceUserData));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: ModifyLoggedInUser ");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_ModifyLoggedInUser"];

        command.Parameters.Add(DeviceId, windowsDeviceUserData.DeviceId);
        command.Parameters.Add(UserName, windowsDeviceUserData.UserName);
        command.Parameters.Add(UserFullName, windowsDeviceUserData.UserFullName);
        command.Parameters.Add(UserDomain, windowsDeviceUserData.UserDomain);
        command.Parameters.Add(UserSId, windowsDeviceUserData.UserSID);
        command.Parameters.Add(WindowsDeviceUserType, (byte)windowsDeviceUserData.WindowsDeviceUserType);
        command.Parameters.Add(CreatedDate, windowsDeviceUserData.CreatedDate);
        command.Parameters.Add(IsMobiControlCreated, windowsDeviceUserData.IsMobiControlCreated);
        command.Parameters.Add(WindowsDeviceUserId, out Ref<int> windowsDeviceUserId);
        command.Parameters.Add(DataKeyId, windowsDeviceUserData.DataKeyId);
        command.ExecuteNonQuery();
        windowsDeviceUserData.WindowsDeviceUserId = windowsDeviceUserId;
    }

    /// <inheritdoc />
    public void LogOffUserByDeviceId(int deviceId)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: LogOffUserByDeviceId ");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_LogOffUserBy_DeviceId"];
        command.Parameters.Add(DeviceId, deviceId);
        command.ExecuteNonQuery();
    }

    /// <inheritdoc />
    public WindowsDeviceUserData GetLoggedInUserDataByDeviceId(int deviceId)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetLoggedInUserDetailsBy_DeviceId"];
        command.Parameters.Add(DeviceId, deviceId);

        return command.ExecuteReader(ReadRecord);
    }

    /// <inheritdoc />
    public IReadOnlyList<WindowsDeviceUserData> GetLoggedInUserDataByDeviceIds(IEnumerable<int> deviceIds)
    {
        var deviceIdsList = deviceIds.AsArray();

        if (deviceIdsList.Count == 0)
        {
            throw new ArgumentNullException(nameof(deviceIds));
        }

        var dataTable = new DataTable("GEN_UDT_NumericIdentifier") { Locale = CultureInfo.InvariantCulture };
        dataTable.Columns.Add(new DataColumn(Id, typeof(int)) { AllowDBNull = false });
        foreach (var deviceId in deviceIdsList)
        {
            dataTable.Rows.Add(deviceId);
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetLoggedInUserDetailsBy_DeviceIds"];
        command.Parameters.Add(DeviceIds, dataTable, SqlDbType.Structured);

        return command.ExecuteReader(ReadLoggedInUserCollection);
    }

    /// <inheritdoc />
    public WindowsDeviceUserSidData GetUserSidByUserNameAndDeviceId(int deviceId, string userName)
    {
        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        if (string.IsNullOrWhiteSpace(userName))
        {
            throw new ArgumentException($"{nameof(userName)} cannot be null or empty");
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetUserSID_ByUserNameAndDeviceId"];
        command.Parameters.Add(DeviceId, deviceId);
        command.Parameters.Add(UserName, userName);

        return command.ExecuteReader(ReadUsedSidRecord);
    }

    /// <inheritdoc />
    public IReadOnlyList<WindowsDeviceUserSidData> GetUserSidsByUserNameAndDeviceIds(IEnumerable<int> deviceIds, string userName)
    {
        var deviceIdsList = deviceIds.AsArray();

        if (deviceIdsList.Count == 0)
        {
            throw new ArgumentException($"{nameof(deviceIds)} cannot be empty");
        }

        if (string.IsNullOrWhiteSpace(userName))
        {
            throw new ArgumentException($"{nameof(userName)} cannot be null or empty");
        }

        var dataTable = new DataTable("GEN_UDT_NumericIdentifier");
        dataTable.Columns.Add(new DataColumn(Id, typeof(int)) { AllowDBNull = false });
        foreach (var deviceId in deviceIdsList)
        {
            dataTable.Rows.Add(deviceId);
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_GetUserSID_ByUserNameAndDeviceIds"];
        command.Parameters.Add(DeviceIds, dataTable, SqlDbType.Structured);
        command.Parameters.Add(UserName, userName);

        return command.ExecuteReader(ReadUserSidList);
    }

    /// <inheritdoc />
    public void UpdateUsernameByUserSidAndDeviceId(string userSid, int deviceId, string newUsername)
    {
        if (string.IsNullOrWhiteSpace(userSid))
        {
            throw new ArgumentException($"{nameof(userSid)} cannot be null or empty");
        }

        if (deviceId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(deviceId));
        }

        if (string.IsNullOrWhiteSpace(newUsername))
        {
            throw new ArgumentException($"{nameof(newUsername)} cannot be null or empty");
        }

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: UpdateUsernameByUserSidAndDeviceId {deviceId} ");
        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_UpdateUsername_ByDeviceIdUserSID"];
        command.Parameters.Add(DeviceId, deviceId);
        command.Parameters.Add(UserSId, userSid);
        command.Parameters.Add(UserName, newUsername);
        command.ExecuteNonQuery();
    }

    /// <inheritdoc />
    public IReadOnlyList<WindowsDeviceUserData> GetUsernameByDeviceIds(IEnumerable<int> deviceIds)
    {
        var deviceIdsList = deviceIds.AsArray();

        if (deviceIdsList.Count == 0)
        {
            throw new ArgumentNullException(nameof(deviceIds));
        }

        var dataTable = new DataTable("GEN_UDT_NumericIdentifier");
        dataTable.Columns.Add(new DataColumn(Id, typeof(int)) { AllowDBNull = false });
        foreach (var deviceId in deviceIdsList)
        {
            dataTable.Rows.Add(deviceId);
        }

        var command = _database.StoredProcedures["dbo.WindowsDeviceUser_Find_ByDeviceIds"];

        command.Parameters.Add(DeviceIds, dataTable, SqlDbType.Structured);

        return command.ExecuteReader(ReadUsernameCollection);
    }

    /// <inheritdoc/>
    public IDictionary<int, int> GetDataKeyIdsByWindowsDeviceUserIds(IEnumerable<int> windowsDeviceUserIds)
    {
        var windowsDeviceUserIdsList = windowsDeviceUserIds.AsArray();

        if (windowsDeviceUserIdsList.Count == 0)
        {
            throw new ArgumentNullException(nameof(windowsDeviceUserIds), "Collection cannot be null or empty");
        }

        var command = _database.CreateStoredProcedureCommand("dbo.Upgrade_V2026_0_0_WindowsDeviceUser_BulkGetDataKeyId");

        var idTable = new DataTable();
        idTable.Columns.Add("Id", typeof(int));

        foreach (var id in windowsDeviceUserIdsList.Distinct())
        {
            idTable.Rows.Add(id);
        }

        command.Parameters.Add(
            parameterName: "WindowsDeviceUserIds",
            value: idTable,
            sqlDbType: SqlDbType.Structured
        );

        var result = command.ExecuteCollection(reader =>
        {
            var deviceUserId = reader.GetInt32(0);
            var dataKeyId = reader.GetInt32(1);
            return new { deviceUserId, dataKeyId };
        });

        return result.ToDictionary(x => x.deviceUserId, x => x.dataKeyId);
    }

    /// <inheritdoc/>
    public void WindowsDeviceUserNameBulkUpdate(IEnumerable<DecryptedLocalUserModel> decryptedUserName)
    {
        var decryptedLocalUserModels = decryptedUserName.AsArray();

        if (decryptedLocalUserModels == null || decryptedLocalUserModels.Count == 0)
        {
            throw new ArgumentNullException(nameof(decryptedUserName), "Input collection cannot be null.");
        }

        var userNames = DecryptedUsersToDataTable(decryptedLocalUserModels);

        _programTrace.Write(TraceLevel.Verbose, LogName, $"WindowsDeviceUserProvider: WindowsDeviceUserNameBulkUpdate {decryptedUserName} ");
        var command = _database.StoredProcedures["[dbo].[Upgrade_2026_0_0_WindowsDeviceUser_BulkUpdate]"];

        command.Parameters.Add("UserNames", userNames, SqlDbType.Structured);

        command.ExecuteNonQuery();
    }

    private static DataTable DecryptedUsersToDataTable(IEnumerable<DecryptedLocalUserModel> entities)
    {
        var scriptDataTable = new DataTable();
        scriptDataTable.Columns.Add("WindowsDeviceUserId", typeof(int)).AllowDBNull = false;
        scriptDataTable.Columns.Add("UserName", typeof(string)).AllowDBNull = false;
        scriptDataTable.Columns.Add("UserFullName", typeof(string)).AllowDBNull = true;

        foreach (var entity in entities)
        {
            scriptDataTable.Rows.Add(entity.WindowsDeviceUserId, entity.UserName, entity.UserFullName);
        }

        return scriptDataTable;
    }

    private static OrdinalColumnMapping GetColumnMapping(IDataRecord reader, bool readDeviceId = true, bool readUserSid = true)
    {
        // OrdinalColumnMapping for Windows Device Local Users.
        return new OrdinalColumnMapping
        {
            WindowsDeviceUserId = reader.GetOrdinal(WindowsDeviceUserId),
            DeviceId = readDeviceId ? reader.GetOrdinal(DeviceId) : default,
            UserSID = readUserSid ? reader.GetOrdinal(UserSId) : default,
            UserName = reader.GetOrdinal(UserName),
            IsMobiControlCreated = reader.GetOrdinal(IsMobiControlCreated),
            AutoGeneratedPassword = reader.GetOrdinal(AutoGeneratedPassword),
            DataKeyId = reader.GetOrdinal(DataKeyId),
            CreatedDate = reader.GetOrdinal(CreatedDate)
        };
    }

    private static OrdinalColumnMapping GetBasicColumnMapping(IDataRecord reader, bool readUserSid = true)
    {
        // OrdinalColumnMapping for Windows Device Local Users Basic Info.
        return new OrdinalColumnMapping
        {
            WindowsDeviceUserId = reader.GetOrdinal(WindowsDeviceUserId),
            UserSID = readUserSid ? reader.GetOrdinal(UserSId) : default,
            UserName = reader.GetOrdinal(UserName),
            IsMobiControlCreated = reader.GetOrdinal(IsMobiControlCreated),
            DataKeyId = reader.GetOrdinal(DataKeyId)
        };
    }

    private static OrdinalColumnMapping GetBasicDetailsColumnMapping(IDataRecord reader)
    {
        // OrdinalColumnMapping for Windows Device Local Users Basic Info.
        return new OrdinalColumnMapping
        {
            WindowsDeviceUserId = reader.GetOrdinal(WindowsDeviceUserId),
            DeviceId = reader.GetOrdinal(DeviceId),
            UserGroups = reader.GetOrdinal(UserGroups)
        };
    }

    private static OrdinalColumnMapping GetLocalUserPasswordMapping(IDataRecord reader)
    {
        // OrdinalColumnMapping for Windows Device Local Users Password Info.
        return new OrdinalColumnMapping
        {
            UserName = reader.GetOrdinal(UserName),
            AutoGeneratedPassword = reader.GetOrdinal(AutoGeneratedPassword),
            DataKeyId = reader.GetOrdinal(DataKeyId)
        };
    }

    private static OrdinalColumnMapping GetUsernameColumnMapping(IDataRecord reader)
    {
        // OrdinalColumnMapping for Windows Device Local Username.
        return new OrdinalColumnMapping
        {
            WindowsDeviceUserId = reader.GetOrdinal(WindowsDeviceUserId),
            DeviceId = reader.GetOrdinal(DeviceId),
            UserName = reader.GetOrdinal(UserName),
        };
    }

    private static OrdinalColumnMapping GetLoggedInUserOrdinalColumnMapping(IDataRecord reader)
    {
        // OrdinalColumnMapping for Windows Device Logged-In Users.
        return new OrdinalColumnMapping
        {
            WindowsDeviceUserId = reader.GetOrdinal(WindowsDeviceUserId),
            UserSID = reader.GetOrdinal(UserSId),
            UserName = reader.GetOrdinal(UserName),
            WindowsDeviceUserType = reader.GetOrdinal(WindowsDeviceUserType),
            UserDomain = reader.GetOrdinal(UserDomain),
            UserFullName = reader.GetOrdinal(UserFullName),
            LastCheckInDeviceUserTime = reader.GetOrdinal(LastCheckInDeviceUserTime),
            DeviceId = GetDeviceIdOrdinal(reader),
            DataKeyId = reader.GetOrdinal(DataKeyId)
        };
    }

    private static OrdinalColumnMapping GetUserSidOrdinalColumnMapping(IDataRecord reader)
    {
        // OrdinalColumnMapping for Windows Device User SID.
        return new OrdinalColumnMapping
        {
            UserSID = reader.GetOrdinal(UserSId),
            DeviceId = GetDeviceIdOrdinal(reader)
        };
    }

    private static WindowsDeviceUserData ParseEntity(IDataRecord reader, OrdinalColumnMapping mapping, int? deviceId = null, string userSid = null)
    {
        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = reader.GetInt32(mapping.WindowsDeviceUserId),
            DeviceId = deviceId ?? reader.GetInt32(mapping.DeviceId),
            UserSID = !string.IsNullOrEmpty(userSid) ? userSid : reader.GetString(mapping.UserSID),
            UserName = reader.GetString(mapping.UserName),
            IsMobiControlCreated = reader.GetBoolean(mapping.IsMobiControlCreated),
            AutoGeneratedPassword = (byte[])reader.GetValue(mapping.AutoGeneratedPassword),
            DataKeyId = reader.GetInt32(mapping.DataKeyId),
            CreatedDate = reader.GetDateTime(mapping.CreatedDate)
        };
    }

    private static WindowsDeviceUserData LocalUserParseEntity(IDataRecord reader, OrdinalColumnMapping mapping)
    {
        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = reader.GetInt32(mapping.WindowsDeviceUserId),
            DeviceId = reader.GetInt32(mapping.DeviceId),
            UserGroups = reader.GetString(mapping.UserGroups)?.Split([","], StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim())
        };
    }

    private static WindowsDeviceUserData LoggedInUserParseEntity(IDataRecord reader, OrdinalColumnMapping mapping)
    {
        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = reader.GetInt32(mapping.WindowsDeviceUserId),
            UserName = reader.GetString(mapping.UserName),
            UserSID = reader.GetString(mapping.UserSID),
            UserDomain = reader.GetString(mapping.UserDomain),
            UserFullName = reader.GetString(mapping.UserFullName),
            WindowsDeviceUserType = (WindowsDeviceUserType)reader.GetByte(mapping.WindowsDeviceUserType),
            LastCheckInDeviceUserTime = reader.GetDateTime(mapping.LastCheckInDeviceUserTime),
            DeviceId = mapping.DeviceId != -1 ? reader.GetInt32(mapping.DeviceId) : 0,
            DataKeyId = reader.GetInt32(mapping.DataKeyId)
        };
    }

    private static WindowsDeviceUserSidData UserSidParseEntity(IDataRecord reader, OrdinalColumnMapping mapping)
    {
        return new WindowsDeviceUserSidData
        {
            UserSID = reader.GetString(mapping.UserSID),
            DeviceId = mapping.DeviceId != -1 ? reader.GetInt32(mapping.DeviceId) : 0
        };
    }

    private static WindowsDeviceUserData ParseBasicEntity(IDataRecord reader, OrdinalColumnMapping mapping, string userSid = null)
    {
        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = reader.GetInt32(mapping.WindowsDeviceUserId),
            UserSID = !string.IsNullOrEmpty(userSid) ? userSid : reader.GetString(mapping.UserSID),
            UserName = reader.GetString(mapping.UserName),
            IsMobiControlCreated = reader.GetBoolean(mapping.IsMobiControlCreated),
            DataKeyId = reader.GetInt32(mapping.DataKeyId)
        };
    }

    private static WindowsDeviceUserData ParseLocalUserPasswordEntity(IDataRecord reader, OrdinalColumnMapping mapping)
    {
        return new WindowsDeviceUserData
        {
            UserName = reader.GetString(mapping.UserName),
            AutoGeneratedPassword = (byte[])reader.GetValue(mapping.AutoGeneratedPassword),
            DataKeyId = reader.GetInt32(mapping.DataKeyId)
        };
    }

    private static WindowsDeviceUserData ParseUsernameDataEntity(IDataRecord reader, OrdinalColumnMapping mapping)
    {
        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = reader.GetInt32(mapping.WindowsDeviceUserId),
            DeviceId = reader.GetInt32(mapping.DeviceId),
            UserName = reader.GetString(mapping.UserName),
        };
    }

    private static List<WindowsDeviceUserData> ReadCollection(IDataReader reader, int? deviceId = null, string userSid = null)
    {
        var result = new List<WindowsDeviceUserData>();
        var mapping = GetColumnMapping(reader, !deviceId.HasValue, userSid == null);
        while (reader.Read())
        {
            result.Add(ParseEntity(reader, mapping, deviceId, userSid));
        }

        return result;
    }

    private static IReadOnlyList<WindowsDeviceUserData> ReadUsernameCollection(IDataReader reader)
    {
        var result = new List<WindowsDeviceUserData>();
        var mapping = GetUsernameColumnMapping(reader);
        while (reader.Read())
        {
            result.Add(ParseUsernameDataEntity(reader, mapping));
        }

        return result;
    }

    private static IReadOnlyList<WindowsDeviceUserData> ReadLocalUserCollection(IDataReader reader)
    {
        var result = new List<WindowsDeviceUserData>();
        var mapping = GetBasicDetailsColumnMapping(reader);
        while (reader.Read())
        {
            result.Add(LocalUserParseEntity(reader, mapping));
        }

        return result;
    }

    private static List<WindowsDeviceUserData> ReadBasicCollection(IDataReader reader, string userSid = null)
    {
        var result = new List<WindowsDeviceUserData>();
        var mapping = GetBasicColumnMapping(reader, userSid == null);
        while (reader.Read())
        {
            result.Add(ParseBasicEntity(reader, mapping, userSid));
        }

        return result;
    }

    private static IReadOnlyCollection<WindowsDeviceUserData> ReadLocalUserPasswordDetails(IDataReader reader)
    {
        var result = new List<WindowsDeviceUserData>();
        var mapping = GetLocalUserPasswordMapping(reader);
        while (reader.Read())
        {
            result.Add(ParseLocalUserPasswordEntity(reader, mapping));
        }

        return result;
    }

    private static IReadOnlyList<WindowsDeviceUserData> ReadLoggedInUserCollection(IDataReader reader)
    {
        var result = new List<WindowsDeviceUserData>();
        var mapping = GetLoggedInUserOrdinalColumnMapping(reader);

        while (reader.Read())
        {
            result.Add(LoggedInUserParseEntity(reader, mapping));
        }

        return result;
    }

    private static WindowsDeviceUserData ReadRecord(IDataReader reader)
    {
        return reader.Read() ? LoggedInUserParseEntity(reader, GetLoggedInUserOrdinalColumnMapping(reader)) : null;
    }

    private static IReadOnlyList<WindowsDeviceUserSidData> ReadUserSidList(IDataReader reader)
    {
        var result = new List<WindowsDeviceUserSidData>();
        var mapping = GetUserSidOrdinalColumnMapping(reader);

        while (reader.Read())
        {
            result.Add(UserSidParseEntity(reader, mapping));
        }

        return result;
    }

    private static WindowsDeviceUserSidData ReadUsedSidRecord(IDataReader reader)
    {
        return reader.Read() ? UserSidParseEntity(reader, GetUserSidOrdinalColumnMapping(reader)) : null;
    }

    private static DataTable CreateDataTable_Bulk_Modify(IEnumerable<WindowsDeviceUserData> windowsDeviceUserData)
    {
        var dataTable = new DataTable("dbo.UDTTable_WindowsDeviceUser_BulkModify");
        dataTable.Columns.AddRange(new[]
        {
            new DataColumn(DeviceId, typeof(int)) { AllowDBNull = false },
            new DataColumn(UserSId, typeof(string)) { AllowDBNull = false },
            new DataColumn(UserName, typeof(string)) { AllowDBNull = false },
            new DataColumn(UserGroups, typeof(string)) { AllowDBNull = true },
            new DataColumn(IsMobiControlCreated, typeof(bool)) { AllowDBNull = false },
            new DataColumn(AutoGeneratedPassword, typeof(byte[])) { AllowDBNull = true },
            new DataColumn(DataKeyId, typeof(int)) { AllowDBNull = false },
            new DataColumn(CreatedDate, typeof(DateTime)) { AllowDBNull = false }
        });

        foreach (var user in windowsDeviceUserData)
        {
            dataTable.Rows.Add(
                user.DeviceId,
                user.UserSID,
                user.UserName,
                null,
                user.IsMobiControlCreated,
                user.AutoGeneratedPassword,
                user.DataKeyId,
                user.CreatedDate);
        }

        return dataTable;
    }

    private static int GetDeviceIdOrdinal(IDataRecord reader)
    {
        try
        {
            return reader.GetOrdinal(DeviceId);
        }
        catch (IndexOutOfRangeException)
        {
            // If the "DeviceId" column is not found, return -1.
            // This is necessary as some stored procedures might not select the DeviceId column.
            return -1;
        }
    }

    private static IReadOnlyList<WindowsDeviceLocalUserModel> ReadLocalUserNamesList(IDataReader reader)
    {
        var result = new List<WindowsDeviceLocalUserModel>();
        var mapping = GetLocalUserNamesColumnMapping(reader);
        while (reader.Read())
        {
            result.Add(ParseLocalUserNamesEntity(reader, mapping));
        }

        return result;
    }

    private static OrdinalColumnMapping GetLocalUserNamesColumnMapping(IDataRecord record)
    {
        return new OrdinalColumnMapping
        {
            WindowsDeviceUserId = record.GetOrdinal(WindowsDeviceUserId),
            UserSID = record.GetOrdinal(UserSId),
            UserName = record.GetOrdinal(UserName)
        };
    }

    private static WindowsDeviceLocalUserModel ParseLocalUserNamesEntity(IDataRecord record, OrdinalColumnMapping mapping)
    {
        return new WindowsDeviceLocalUserModel
        {
            WindowsDeviceLocalUserId = record.GetInt32(mapping.WindowsDeviceUserId),
            SID = record.GetString(mapping.UserSID),
            UserName = record.GetString(mapping.UserName)
        };
    }

    /// <summary>
    ///  Internal struct that caches column name-ordinal mapping.
    /// </summary>
    private class OrdinalColumnMapping
    {
        public int WindowsDeviceUserId { get; internal set; }

        public int DeviceId { get; internal set; }

        public int UserSID { get; internal set; }

        public int UserName { get; internal set; }

        public int UserGroups { get; internal set; }

        public int IsMobiControlCreated { get; internal set; }

        public int AutoGeneratedPassword { get; internal set; }

        public int DataKeyId { get; internal set; }

        public int CreatedDate { get; internal set; }

        public int UserDomain { get; internal set; }

        public int UserFullName { get; internal set; }

        public int WindowsDeviceUserType { get; internal set; }

        public int LastCheckInDeviceUserTime { get; internal set; }
    }
}
