using System;
using NUnit.Framework;
using Soti.MobiControl.Events;
using Soti.MobiControl.WindowsModern.Implementation.Events;

namespace Soti.MobiControl.WindowsModern.Implementation.Tests.Events
{
    internal class LocalUserDeletedFromDeviceEventTests
    {
        [Test]
        public void ViewedAutoGeneratedPassword_Test()
        {
            const int deviceId = 100001;
            var devId = Guid.NewGuid().ToString();
            const string userName = "UserName";
            var testEvent = new LocalUserDeletedFromDeviceEvent(deviceId, devId, userName);
            Assert.That(testEvent.EventSeverity, Is.EqualTo(EventSeverity.Information));
            Assert.That(testEvent.DeviceId, Is.EqualTo(deviceId));
            Assert.That(testEvent.DevId, Is.EqualTo(devId));
            Assert.That(testEvent.EventAdditionalParameters[0], Is.EqualTo(userName));
        }
    }
}
