using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Moq;
using NUnit.Framework;
using Soti.Diagnostics;
using Soti.MobiControl.Devices;
using Soti.MobiControl.Events;
using Soti.MobiControl.Exceptions;
using Soti.MobiControl.Search.Database;
using Soti.MobiControl.WindowsModern.Implementation.Events;
using Soti.MobiControl.WindowsModern.Implementation.Models;
using Soti.MobiControl.WindowsModern.Implementation.Providers;
using Soti.MobiControl.WindowsModern.Models;
using Soti.MobiControl.WindowsModern.Models.Enums;
using Soti.SensitiveDataProtection;
using Soti.SensitiveDataProtection.Model;

namespace Soti.MobiControl.WindowsModern.Implementation.Tests;

[TestFixture]
public class WindowsDeviceLocalUsersServiceTests
{
    private readonly DeviceKeyInformation _device = new(1, "s1a2a3s4e65e4e5", DevicePlatform.Windows);
    private Mock<IDataKeyService> _dataKeyServiceMock;
    private Mock<ISensitiveDataEncryptionService> _sensitiveDataEncryptionServiceMock;
    private Mock<IWindowsDeviceUserProvider> _windowsDeviceUserProviderMock;
    private Mock<IWindowsDeviceLocalGroupsService> _windowsDeviceLocalGroupsServiceMock;
    private Mock<IProgramTrace> _programTraceMock;
    private Mock<IEventDispatcher> _eventDispatcherMock;
    private Mock<IDeviceKeyInformationRetrievalService> _deviceKeyInformationRetrievalServiceMock;
    private Mock<IWindowsDeviceLocalGroupProvider> _windowsDeviceLocalGroupProviderMock;
    private Mock<IDeviceSearchInfoService> _deviceSearchInfoServiceMock;
    private IWindowsDeviceLocalUsersService _windowsDeviceLocalUsersService;
    private Mock<ITmpWindowsDeviceUserDataProvider> _tmpWindowsDeviceUserDataProviderMock;

    private static IEnumerable<TestCaseData> LocalUserDataTestCases
    {
        get
        {
            var currentDateTime = DateTime.Now;
            var passwordModifiedDate = currentDateTime.AddDays(2);

            yield return new TestCaseData(
                new TestData
                {
                    SameUser = false,
                    DeviceId = 1,
                    LocalUserKeysData = "UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Administrators#UserSid:S-1-5-21-429203459-4144766043-3079164071-503,UserName:DefaultAccount,PasswordLastModified:2024-02-14T10:25:15Z,Groups:System Managed Accounts Group#UserSid:S-1-5-21-429203459-4144766043-3079164071-501,UserName:Guest,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Guests#UserSid:S-1-5-21-429203459-4144766043-3079164071-1012,UserName:TestUser,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Administrators,Users#UserSid:S-1-5-21-429203459-4144766043-3079164071-1013,UserName:TestUser1,PasswordLastModified:2024-02-14T10:25:15Z,Groups:#UserSid:S-1-5-21-429203459-4144766043-3079164071-1014,UserName:TestUser3,PasswordLastModified:2024-02-14T10:25:15Z,Groups:#UserSid:S-1-5-21-429203459-4144766043-3079164071-1001,UserName:User,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Administrators,Users#UserSid:S-1-5-21-429203459-4144766043-3079164071-504,UserName:WDAGUtilityAccount,PasswordLastModified:2024-02-14T10:25:15Z,Groups:#",
                    LocalUsersFromDb = null,
                    GroupNamesFromDb = []
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = false,
                    DeviceId = 1,
                    LocalUserKeysData = null,
                    LocalUsersFromDb = null,
                    GroupNamesFromDb = []
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = false,
                    DeviceId = 1,
                    LocalUserKeysData = "unparsable",
                    LocalUsersFromDb = null,
                    GroupNamesFromDb = []
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = true,
                    DeviceId = 1,
                    LocalUserKeysData = "UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-21-429203459-4144766043-3079164071-500",
                            UserName = "Administrator",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = "password"u8.ToArray(),
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = false,
                    DeviceId = 1,
                    LocalUserKeysData = "UserSid:S-1-5-20-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-21-429203459-4144766043-3079164071-500",
                            UserName = "Administrator2",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = "password"u8.ToArray(),
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = true,
                    DeviceId = 1,
                    LocalUserKeysData = "UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:2024-02-14T10:25:15Z,Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-21-429203459-4144766043-3079164071-500",
                            UserName = "Administrator",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = "password"u8.ToArray(),
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = true,
                    DeviceId = 1,
                    LocalUserKeysData = $"UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:{passwordModifiedDate.ToUniversalTime().ToString(CultureInfo.InvariantCulture)},Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-21-429203459-4144766043-3079164071-500",
                            UserName = "Administrator",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = "oldPassword"u8.ToArray(),
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = true,
                    DeviceId = 1,
                    LocalUserKeysData = $"UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:{passwordModifiedDate.ToUniversalTime().ToString(CultureInfo.InvariantCulture)},Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-21-429203459-4144766043-3079164071-500",
                            UserName = "Administrator",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = null,
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = false,
                    DeviceId = 1,
                    LocalUserKeysData = $"UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:{passwordModifiedDate.ToUniversalTime().ToString(CultureInfo.InvariantCulture)},Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-22-429203459-4144766043-3079164071-500",
                            UserName = "Administrator",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = null,
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
            yield return new TestCaseData(
                new TestData
                {
                    SameUser = false,
                    DeviceId = 1,
                    LocalUserKeysData = $"UserSid:S-1-5-21-429203459-4144766043-3079164071-500,UserName:Administrator,PasswordLastModified:{passwordModifiedDate.ToUniversalTime().ToString(CultureInfo.InvariantCulture)},Groups:Administrators#UserSid:S-1-5-22-429203459-4144766043-3079164071-501,UserName:BeforeRename,PasswordLastModified:{passwordModifiedDate.ToUniversalTime().ToString(CultureInfo.InvariantCulture)},Groups:Administrators#",
                    LocalUsersFromDb =
                    [
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-22-429203459-4144766043-3079164071-500",
                            UserName = "Administrator",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = null,
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        },
                        new WindowsDeviceUserTestData
                        {
                            WindowsDeviceUserId = 1,
                            UserSID = "S-1-5-22-429203459-4144766043-3079164071-501",
                            UserName = "AfterRename",
                            DeviceId = 1,
                            IsMobiControlCreated = true,
                            AutoGeneratedPassword = null,
                            DataKeyId = 1,
                            CreatedDate = currentDateTime
                        }
                    ],
                    GroupNamesFromDb =
                    [
                        new WindowsDeviceUserGroupNameTestData
                        {
                            WindowsDeviceUserId = 1,
                            WindowsDeviceLocalGroup = 1,
                            LocalGroupName = "Administrator"
                        }
                    ]
                });
        }
    }

    [SetUp]
    public void Setup()
    {
        _dataKeyServiceMock = new Mock<IDataKeyService>(MockBehavior.Strict);
        _sensitiveDataEncryptionServiceMock = new Mock<ISensitiveDataEncryptionService>(MockBehavior.Strict);
        _windowsDeviceUserProviderMock = new Mock<IWindowsDeviceUserProvider>(MockBehavior.Strict);
        _tmpWindowsDeviceUserDataProviderMock = new Mock<ITmpWindowsDeviceUserDataProvider>(MockBehavior.Strict);
        _windowsDeviceLocalGroupsServiceMock = new Mock<IWindowsDeviceLocalGroupsService>(MockBehavior.Strict);
        _programTraceMock = new Mock<IProgramTrace>(MockBehavior.Strict);
        _eventDispatcherMock = new Mock<IEventDispatcher>(MockBehavior.Strict);
        _deviceKeyInformationRetrievalServiceMock =
            new Mock<IDeviceKeyInformationRetrievalService>(MockBehavior.Strict);
        _windowsDeviceLocalGroupProviderMock = new Mock<IWindowsDeviceLocalGroupProvider>(MockBehavior.Default);
        _deviceSearchInfoServiceMock = new Mock<IDeviceSearchInfoService>(MockBehavior.Default);
        _windowsDeviceLocalUsersService = new WindowsDeviceLocalUsersService(
            _programTraceMock.Object,
            _windowsDeviceUserProviderMock.Object,
            _tmpWindowsDeviceUserDataProviderMock.Object,
            _windowsDeviceLocalGroupsServiceMock.Object,
            _dataKeyServiceMock.Object,
            _eventDispatcherMock.Object,
            _deviceKeyInformationRetrievalServiceMock.Object,
            _sensitiveDataEncryptionServiceMock.Object,
            _windowsDeviceLocalGroupProviderMock.Object,
            _deviceSearchInfoServiceMock.Object);
    }

    [Test]
    public void ConstructorTests()
    {
        var argumentCount = 1;
        for (var i = 0; i < argumentCount; i++)
        {
            var j = 0;
            Assert.Throws<ArgumentNullException>(() => _ = new WindowsDeviceLocalUsersService(
                i == j++ ? null : _programTraceMock.Object,
                i == j++ ? null : _windowsDeviceUserProviderMock.Object,
                i == j++ ? null : _tmpWindowsDeviceUserDataProviderMock.Object,
                i == j++ ? null : _windowsDeviceLocalGroupsServiceMock.Object,
                i == j++ ? null : _dataKeyServiceMock.Object,
                i == j++ ? null : _eventDispatcherMock.Object,
                i == j++ ? null : _deviceKeyInformationRetrievalServiceMock.Object,
                i == j++ ? null : _sensitiveDataEncryptionServiceMock.Object,
                i == j++ ? null : _windowsDeviceLocalGroupProviderMock.Object,
                i == j++ ? null : _deviceSearchInfoServiceMock.Object));

            argumentCount = j;
        }
    }

    [Test]
    public void DeleteLocalUserKeysData_Throws_ArgumentOutOfRangeException_Exceptions()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.DeleteUserData(0, true));
    }

    [Test]
    public void CleanLocalUsers_Throws_ArgumentOutOfRangeException_Exceptions()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.DeleteUserData(0, true));
    }

    [Test]
    public void CleanLocalUsers_Succeeds()
    {
        _windowsDeviceUserProviderMock.Setup(m => m.DeleteByDeviceId(1, null));
        _programTraceMock
            .Setup(x => x.Write(It.IsAny<TraceLevel>(), It.IsAny<string>(), It.IsAny<string>()));

        _windowsDeviceLocalUsersService.DeleteUserData(1);

        _windowsDeviceUserProviderMock
            .Verify(m => m.DeleteByDeviceId(1, null), Times.Once);
    }

    [Test]
    public void GetLocalUserByDeviceIdAndSid_Throws_ArgumentOutOfRangeException_Exception()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GetLocalUserByDeviceIdAndSid(0, "sid"));
    }

    [TestCaseSource(nameof(GetInvalidSid))]
    public void GetDeviceLocalUserByDeviceIdAndSID_Throws_Argument_Exception(string sid)
    {
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GetLocalUserByDeviceIdAndSid(1, sid));
    }

    [Test]
    public void GetLocalUserByDeviceIdAndSid_Throws_Security_Exception()
    {
        _windowsDeviceUserProviderMock
            .Setup(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>())).Returns((WindowsDeviceUserData)null);
        Assert.Throws<InternalLogicException>(() => _windowsDeviceLocalUsersService.GetLocalUserByDeviceIdAndSid(1, "sid1"));
    }

    [Test]
    public void GetLocalUserByDeviceIdAndSID_Success()
    {
        var localUserData = new WindowsDeviceUserData()
        {
            WindowsDeviceUserId = 1,
            UserName = "userName3",
            DeviceId = 11,
            IsMobiControlCreated = true,
            UserSID = "string2",
            DataKeyId = 1,
            AutoGeneratedPassword = "SamplePassword"u8.ToArray(),
        };

        var userGroupNamesWithIds = new List<WindowsDeviceLocalGroupUserGroupNameData>
        {
            CreateWindowsDeviceUserGroupNameData(1, 1, "user-group1"),
            CreateWindowsDeviceUserGroupNameData(1, 2, "user-group2"),
            CreateWindowsDeviceUserGroupNameData(1, 3, "user-group3"),
        };
        var userGroupsLookup = GetUserGroupsLookup(userGroupNamesWithIds);
        var dataKey = GetDataKey(1);
        _windowsDeviceUserProviderMock.Setup(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>())).Returns(localUserData);
        _dataKeyServiceMock.Setup(service => service.GetKey(dataKey.Id)).Returns(dataKey);
        _windowsDeviceLocalGroupsServiceMock.Setup(x => x.GetUserGroupsByWindowsDeviceUserIds(It.IsAny<IReadOnlyList<int>>())).Returns(userGroupsLookup);
        _sensitiveDataEncryptionServiceMock
            .Setup(x => x.Decrypt(localUserData.AutoGeneratedPassword, dataKey))
            .Returns("SamplePassword"u8.ToArray());
        Assert.DoesNotThrow(() => _windowsDeviceLocalUsersService.GetLocalUserByDeviceIdAndSid(localUserData.DeviceId, localUserData.UserSID));
        var result = _windowsDeviceLocalUsersService.GetLocalUserByDeviceIdAndSid(localUserData.DeviceId, localUserData.UserSID);
        Assert.NotNull(result);
        Assert.AreEqual(localUserData.UserName, result.UserName);
        Assert.AreEqual(localUserData.DeviceId, result.DeviceId);
        Assert.AreEqual(localUserData.IsMobiControlCreated, result.IsMobiControlCreated);
        Assert.AreEqual("string2", result.SID);
        Assert.AreEqual(new List<string> { "user-group1", "user-group2", "user-group3" }, result.UserGroups);
        Assert.AreEqual("SamplePassword", result.AutoGeneratedPassword);
    }

    [Test]
    public void GetLocalUserNamesByDeviceIdAndSids_InvalidDeviceId_ThrowsArgumentOutOfRangeException()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GetLocalUserNamesByDeviceIdAndSids(0, ["sid"]));
    }

    [Test]
    public void GetLocalUserNamesByDeviceIdAndSids_NullUserSids_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.GetLocalUserNamesByDeviceIdAndSids(1, null));
    }

    [Test]
    public void GetLocalUserNamesByDeviceIdAndSids_EmptyUserSids_ReturnsEmptyList()
    {
        Assert.That(_windowsDeviceLocalUsersService.GetLocalUserNamesByDeviceIdAndSids(1, []), Is.Empty);
    }

    [Test]
    public void GetLocalUserNamesByDeviceIdAndSids_UserNotFoundInDb()
    {
        _windowsDeviceUserProviderMock
            .Setup(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>()))
            .Returns((WindowsDeviceUserData)null).Verifiable();

        var result = _windowsDeviceLocalUsersService.GetLocalUserNamesByDeviceIdAndSids(1, ["sid"]);

        _windowsDeviceUserProviderMock
            .Verify(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>()), Times.Once);

        Assert.That(result, Is.Empty);
    }

    [Test]
    public void GetLocalUserNamesByDeviceIdAndSids_Success_SingleUser()
    {
        var userData = new WindowsDeviceUserData
        {
            WindowsDeviceUserId = 101,
            UserSID = "sid",
            UserName = "userName"
        };

        _windowsDeviceUserProviderMock
            .Setup(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>()))
            .Returns(userData).Verifiable();

        var result = _windowsDeviceLocalUsersService.GetLocalUserNamesByDeviceIdAndSids(1, ["sid"]);

        _windowsDeviceUserProviderMock
            .Verify(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>()), Times.Once);

        Assert.IsNotNull(result);
        Assert.AreEqual(1, result.Count);
        Assert.AreEqual(userData.WindowsDeviceUserId, result[0].WindowsDeviceLocalUserId);
        Assert.AreEqual(userData.UserSID, result[0].SID);
        Assert.AreEqual(userData.UserName, result[0].UserName);
    }

    [Test]
    public void GetLocalUserNamesByDeviceIdAndSids_Success_MultipleUsers()
    {
        var userData = new List<WindowsDeviceLocalUserModel>
        {
            new()
            {
                WindowsDeviceLocalUserId = 101,
                SID = "sid1",
                UserName = "userName1"
            },
            new()
            {
                WindowsDeviceLocalUserId = 102,
                SID = "sid2",
                UserName = "userName2"
            }
        };

        _windowsDeviceUserProviderMock
            .Setup(x => x.GetLocalUserNamesByDeviceIdAndSids(It.IsAny<int>(), It.IsAny<IEnumerable<string>>()))
            .Returns(userData).Verifiable();

        var result = _windowsDeviceLocalUsersService.GetLocalUserNamesByDeviceIdAndSids(1, ["sid1", "sid2"]);

        _windowsDeviceUserProviderMock
            .Verify(x => x.GetLocalUserNamesByDeviceIdAndSids(It.IsAny<int>(), It.IsAny<IEnumerable<string>>()), Times.Once);

        Assert.IsNotNull(result);
        Assert.AreEqual(2, result.Count);
        for (var i = 0; i < 2; ++i)
        {
            Assert.AreEqual(userData[i].WindowsDeviceLocalUserId, result[i].WindowsDeviceLocalUserId);
            Assert.AreEqual(userData[i].SID, result[i].SID);
            Assert.AreEqual(userData[i].UserName, result[i].UserName);
        }
    }

    [Test]
    public void GetLocalUserPasswordByDeviceIdAndSID_Throws_ArgumentOutOfRangeException_Exception()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GetLocalUserPasswordByDeviceIdAndSid(0, "sid"));
    }

    [TestCaseSource(nameof(GetInvalidSid))]
    public void GetLocalUserPasswordByDeviceIdAndSID_Throws_Argument_Exception(string sid)
    {
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GetLocalUserPasswordByDeviceIdAndSid(1, sid));
    }

    [Test]
    public void GetLocalUserPasswordByDeviceIdAndSID_Success()
    {
        var localUserData = new WindowsDeviceUserData()
        {
            UserName = "userName3",
            DeviceId = 11,
            UserSID = "string2",
            DataKeyId = 1,
            AutoGeneratedPassword = "SamplePassword"u8.ToArray(),
        };
        var dataKey = GetDataKey(1);
        _windowsDeviceUserProviderMock.Setup(x => x.GetLocalUsersPasswordByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>())).Returns(localUserData);
        _dataKeyServiceMock.Setup(service => service.GetKey(dataKey.Id)).Returns(dataKey);
        _sensitiveDataEncryptionServiceMock
            .Setup(x => x.Decrypt(localUserData.AutoGeneratedPassword, dataKey))
            .Returns("SamplePassword"u8.ToArray());
        Assert.DoesNotThrow(() => _windowsDeviceLocalUsersService.GetLocalUserPasswordByDeviceIdAndSid(localUserData.DeviceId, localUserData.UserSID));
        var result = _windowsDeviceLocalUsersService.GetLocalUserPasswordByDeviceIdAndSid(localUserData.DeviceId, localUserData.UserSID);
        Assert.NotNull(result);
        Assert.AreEqual(localUserData.UserName, result.UserName);
        Assert.AreEqual("SamplePassword", result.AutoGeneratedPassword);
    }

    [Test]
    public void GetLocalUserPasswordByDeviceIdAndSid_Success_NoAutogeneratedPassword()
    {
        const int deviceId = 10;
        const string userSid = "UserSid";
        _windowsDeviceUserProviderMock
            .Setup(x => x.GetLocalUsersPasswordByDeviceIdAndSid(deviceId, userSid))
            .Returns(null as WindowsDeviceUserData);

        var result = _windowsDeviceLocalUsersService.GetLocalUserPasswordByDeviceIdAndSid(deviceId, userSid);

        Assert.IsNull(result);
    }

    [Test]
    public void GetDeviceLocalUsersSummaryInfo_Success()
    {
        const int deviceId = 11;
        var dataKey = GetDataKey(1);
        var localUserData1 = CreateLocalUserData(1, "userName1", deviceId, false, "string1", dataKey.Id);
        var localUserData2 = CreateLocalUserData(2, "userName2", deviceId, true, "string2", dataKey.Id);
        var userGroupNamesWithIds = new List<WindowsDeviceLocalGroupUserGroupNameData>
        {
            CreateWindowsDeviceUserGroupNameData(1, 1, "user-group1"),
            CreateWindowsDeviceUserGroupNameData(1, 2, "user-group2"),
            CreateWindowsDeviceUserGroupNameData(2, 1, "user-group1"),
            CreateWindowsDeviceUserGroupNameData(2, 2, "user-group2"),
            CreateWindowsDeviceUserGroupNameData(2, 3, "user-group3")
        };
        var userGroupsLookup = GetUserGroupsLookup(userGroupNamesWithIds);
        _windowsDeviceUserProviderMock.Setup(x => x.GetAllLocalUsersBasicDataByDeviceId(deviceId))
            .Returns(new List<WindowsDeviceUserData> { localUserData1, localUserData2 });
        _windowsDeviceLocalGroupsServiceMock.Setup(x => x.GetUserGroupsByWindowsDeviceUserIds(It.IsAny<IEnumerable<int>>())).Returns(userGroupsLookup);
        _dataKeyServiceMock.Setup(service => service.GetKey(dataKey.Id)).Returns(dataKey);

        Assert.DoesNotThrow(() => _windowsDeviceLocalUsersService.GetDeviceLocalUsersSummaryInfo(deviceId));

        var res = _windowsDeviceLocalUsersService.GetDeviceLocalUsersSummaryInfo(deviceId).ToList();
        var result1 = res.Find(x => x.UserName == "userName1");
        var result2 = res.Find(x => x.UserName == "userName2");

        Assert.NotNull(res);
        Assert.AreEqual(2, res.Count);
        Assert.AreEqual(localUserData1.UserSID, result1.Sid);
        Assert.AreEqual(localUserData2.UserSID, result2.Sid);
        Assert.AreEqual(new List<string> { "user-group1", "user-group2", "user-group3" }, result2.UserGroups);
        Assert.AreEqual(localUserData1.IsMobiControlCreated, result1.IsMobiControlCreated);
    }

    [Test]
    public void GetDeviceLocalUsersSummary_Success()
    {
        const int deviceId = 11;
        var dataKey = GetDataKey(1);
        var localUserData1 = CreateLocalUserData(1, "userName1", deviceId, false, "string1", dataKey.Id);
        var localUserData2 = CreateLocalUserData(2, "userName2", deviceId, true, "string2", dataKey.Id);

        _windowsDeviceUserProviderMock.Setup(x => x.GetAllLocalUsersData())
            .Returns(new List<WindowsDeviceUserData> { localUserData1, localUserData2 });

        var result = _windowsDeviceLocalUsersService.GetDeviceLocalUsersSummary();
        _windowsDeviceUserProviderMock.Verify(x => x.GetAllLocalUsersData(), Times.Once);
        Assert.AreEqual(2, result.Count());
    }

    [Test]
    public void GetDeviceLocalUsersSummaryInfo_Success_NoUsers()
    {
        const int deviceId = 10;
        _windowsDeviceUserProviderMock
            .Setup(x => x.GetAllLocalUsersBasicDataByDeviceId(deviceId))
            .Returns((IReadOnlyList<WindowsDeviceUserData>)null);
        var result = _windowsDeviceLocalUsersService.GetDeviceLocalUsersSummaryInfo(deviceId);

        Assert.IsNotNull(result);
        Assert.IsEmpty(result);
    }

    [Test]
    public void GetDeviceLocalUsersSummaryInfo_ThrowsException()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GetDeviceLocalUsersSummaryInfo(-1));
    }

    [TestCaseSource(nameof(LocalUserDataTestCases))]
    public void ProcessLocalUsersKeysData_Success(TestData testData)
    {
        var dataKey = GetDataKey(1);

        // Arrange
        _windowsDeviceUserProviderMock.Setup(x => x.GetAllLocalUsersDataByDeviceId(It.IsAny<int>())).Returns(ToWindowsDeviceData(testData.LocalUsersFromDb));
        _windowsDeviceUserProviderMock.Setup(x => x.BulkReplace(It.IsAny<int>(), It.IsAny<IEnumerable<WindowsDeviceUserData>>())).Returns(It.IsAny<Dictionary<string, int>>());
        _windowsDeviceUserProviderMock.Setup(x => x.DeleteByDeviceId(It.IsAny<int>(), WindowsDeviceUserType.Local));
        _windowsDeviceLocalGroupsServiceMock.Setup(x => x.BulkModifyLocalGroupUser(It.IsAny<int>(), It.IsAny<Dictionary<string, List<string>>>(), It.IsAny<Dictionary<string, int>>(), It.IsAny<IEnumerable<WindowsDeviceLocalGroup>>()));
        var userGroups = ToWindowsDeviceGroupNames(testData.GroupNamesFromDb);
        var userGroupsLookup = GetUserGroupsLookup(userGroups);
        _windowsDeviceLocalGroupsServiceMock.Setup(x => x.GetUserGroupsByWindowsDeviceUserIds(It.IsAny<IEnumerable<int>>())).Returns(userGroupsLookup);
        _dataKeyServiceMock.Setup(service => service.GetKey(dataKey.Id)).Returns(dataKey);
        _dataKeyServiceMock.Setup(service => service.GetKey()).Returns(dataKey);
        _sensitiveDataEncryptionServiceMock.Setup(s => s.Encrypt(It.IsAny<byte[]>(), It.IsAny<DataKey>()))
            .Returns("password"u8.ToArray());
        _sensitiveDataEncryptionServiceMock
            .Setup(x => x.Decrypt(It.IsAny<byte[]>(), It.IsAny<DataKey>()))
            .Returns((byte[] password, DataKey _) => password.ToArray());
        _deviceKeyInformationRetrievalServiceMock.Setup(x => x.GetDeviceKeyInformation(It.IsAny<int>()))
            .Returns(_device);
        _eventDispatcherMock.Setup(a => a.DispatchEvent(It.IsAny<IEvent>()));
        _programTraceMock.Setup(x => x.Write(It.IsAny<TraceLevel>(), It.IsAny<string>(), It.IsAny<string>()));

        // Act & Assert
        _windowsDeviceLocalUsersService.SynchronizeLocalUserDataWithSnapshot(testData.DeviceId, testData.LocalUserKeysData, null);
        if (testData.SameUser || testData.LocalUserKeysData == "unparsable")
        {
            return;
        }

        if (testData.LocalUserKeysData == null)
        {
            _windowsDeviceUserProviderMock.Verify(x => x.DeleteByDeviceId(testData.DeviceId, 0), Times.Once);
            return;
        }

        _windowsDeviceUserProviderMock.Verify(x => x.BulkReplace(It.IsAny<int>(), It.IsAny<IEnumerable<WindowsDeviceUserData>>()), Times.Once);
        _programTraceMock.Verify(x => x.Write(It.IsAny<TraceLevel>(), It.IsAny<string>(), It.IsAny<string>()), Times.Once);
        if (testData.LocalUserKeysData != "unparsable" && testData.LocalUserKeysData != null && testData.LocalUsersFromDb == null)
        {
            _dataKeyServiceMock.Verify(x => x.GetKey(), Times.Exactly(8));
            _windowsDeviceLocalGroupsServiceMock.Verify(x => x.BulkModifyLocalGroupUser(It.IsAny<int>(), It.IsAny<Dictionary<string, List<string>>>(), It.IsAny<Dictionary<string, int>>(), It.IsAny<IEnumerable<WindowsDeviceLocalGroup>>()), Times.Once);
            return;
        }

        _dataKeyServiceMock.Verify(x => x.GetKey(), Times.Once);
    }

    [Test]
    public void ProcessLocalUsersKeysData_ArgumentOutOfRangeException()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.SynchronizeLocalUserDataWithSnapshot(0, "LocalUserKeysData", null));
    }

    [Test]
    public void BulkUpdateLocalUsers_Throws_ArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.BulkUpdateLocalUsers(null));
    }

    [Test]
    public void BulkUpdateLocalUsers_Throws_ArgumentException()
    {
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.BulkUpdateLocalUsers(new List<WindowsDeviceLocalUserModel>()));
        var invalidLocalUsersData = new List<WindowsDeviceLocalUserModel>()
        {
            new WindowsDeviceLocalUserModel() { WindowsDeviceLocalUserId = 0, UserName = "Cal", DeviceId = 1, CreatedDate = DateTime.Now, SID = "wewewd", IsMobiControlCreated = true, AutoGeneratedPassword = "12345678", UserGroups = new List<string>() { "g1" } },
            null,
        };
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.BulkUpdateLocalUsers(invalidLocalUsersData));
    }

    [TestCaseSource(nameof(BulkUpdateSuccessData))]
    public void BulkUpdateLocalUsers_Success(List<WindowsDeviceLocalUserModel> localUsersData, int groupNameId, int groupId)
    {
        var i = 1;
        var groupIdAfterUpsert = 4;
        var bulkUpdateOutput = localUsersData.ToDictionary(localUser => localUser.SID, _ => i++);
        _windowsDeviceUserProviderMock.Setup(s => s.Insert(It.IsAny<WindowsDeviceUserData>()));
        _windowsDeviceUserProviderMock.Setup(s => s.BulkUpdate(It.IsAny<IEnumerable<WindowsDeviceUserData>>())).Returns(bulkUpdateOutput);
        var dataKey = GetDataKey(1);
        _dataKeyServiceMock.Setup(service => service.GetKey()).Returns(dataKey);
        _sensitiveDataEncryptionServiceMock.Setup(s => s.Encrypt(It.IsAny<byte[]>(), It.IsAny<DataKey>()))
            .Returns("testPassword"u8.ToArray());
        _windowsDeviceLocalGroupsServiceMock.Setup(s => s.GetGroupNameId(It.IsAny<string>())).Returns(groupNameId);
        _windowsDeviceLocalGroupProviderMock.Setup(s => s.InsertLocalGroupName(It.IsAny<string>(), out groupNameId));
        _windowsDeviceLocalGroupProviderMock.Setup(s => s.UpsertWindowsDeviceLocalGroup(It.IsAny<int>(), It.IsAny<int>(), out groupIdAfterUpsert));
        _windowsDeviceLocalGroupProviderMock.Setup(s => s.GetGroupIdByNameId(It.IsAny<int>(), It.IsAny<int>())).Returns(groupId);
        _windowsDeviceLocalGroupProviderMock.Setup(s => s.InsertLocalGroupUser(It.IsAny<int>(), It.IsAny<int>()));
        _windowsDeviceLocalUsersService.BulkUpdateLocalUsers(localUsersData.ToList());
        var userGroupsCount = localUsersData.Select(s => s.UserGroups.Count()).Sum();
        var distinctUserGroupsCount = localUsersData.SelectMany(s => s.UserGroups).Distinct().Count();
        if (localUsersData.Count == 1)
        {
            _windowsDeviceUserProviderMock.Verify(s => s.Insert(It.IsAny<WindowsDeviceUserData>()), Times.Once);
        }
        else
        {
            _windowsDeviceUserProviderMock.Verify(s => s.BulkUpdate(It.IsAny<IEnumerable<WindowsDeviceUserData>>()), Times.Once);
        }

        if (groupNameId == 0)
        {
            _windowsDeviceLocalGroupProviderMock.Verify(s => s.InsertLocalGroupName(It.IsAny<string>(), out groupNameId), Times.Exactly(distinctUserGroupsCount));
            _windowsDeviceLocalGroupProviderMock.Verify(s => s.UpsertWindowsDeviceLocalGroup(It.IsAny<int>(), It.IsAny<int>(), out groupId), Times.Exactly(distinctUserGroupsCount));
        }
        else
        {
            _windowsDeviceLocalGroupProviderMock.Verify(s => s.UpsertWindowsDeviceLocalGroup(It.IsAny<int>(), It.IsAny<int>(), out groupId), Times.Exactly(distinctUserGroupsCount));
        }
        _windowsDeviceLocalGroupProviderMock.Verify(s => s.InsertLocalGroupUser(It.IsAny<int>(), It.IsAny<int>()), Times.Exactly(userGroupsCount));
    }

    [Test]
    public void DeleteLocalUser_Throws_ArgumentException()
    {
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.DeleteLocalUser(null, 1));
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.DeleteLocalUser("null", 0));
    }

    [Test]
    public void DeleteLocalUser_Success()
    {
        _windowsDeviceUserProviderMock.Setup(s => s.DeleteByUserSid("Success", 1));
        _windowsDeviceLocalUsersService.DeleteLocalUser("Success", 1);
        _windowsDeviceUserProviderMock.Verify(s => s.DeleteByUserSid(It.IsAny<string>(), It.IsAny<int>()), Times.Once);
    }

    [Test]
    public void UpdateLocalUserPassword_Throws_Exception()
    {
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.UpdateLocalUserPassword(null, 1));
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.UpdateLocalUserPassword("userSid", 0));
        _windowsDeviceUserProviderMock.Setup(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>())).Returns((WindowsDeviceUserData)null);
        Assert.Throws<InternalLogicException>(() => _windowsDeviceLocalUsersService.UpdateLocalUserPassword("nonexistentSid", 1));
    }

    [Test]
    public void UpdateLocalUserPassword_Success()
    {
        var localUserData3 = new WindowsDeviceUserData()
        {
            UserName = "userName3",
            DeviceId = 1,
            IsMobiControlCreated = true,
            UserSID = "userSid",
            DataKeyId = 1,
            AutoGeneratedPassword = "SamplePassword"u8.ToArray(),
        };
        var userGroupsLookUp = GetUserGroupsLookup(new List<WindowsDeviceLocalGroupUserGroupNameData>());

        _programTraceMock.Setup(x => x.Write(It.IsAny<TraceLevel>(), It.IsAny<string>(), It.IsAny<string>()));
        _dataKeyServiceMock.Setup(d => d.GetKey()).Returns(new DataKey { Id = 1 });
        _dataKeyServiceMock.Setup(d => d.GetKey(It.IsAny<int>())).Returns(new DataKey { Id = 1 });
        _sensitiveDataEncryptionServiceMock.Setup(x => x.Decrypt(It.IsAny<byte[]>(), It.IsAny<DataKey>())).Returns("SamplePassword"u8.ToArray());
        _windowsDeviceUserProviderMock.Setup(s => s.ResetPassword(It.IsAny<int>()));
        _windowsDeviceUserProviderMock.Setup(x => x.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>())).Returns(localUserData3);
        _windowsDeviceLocalGroupsServiceMock.Setup(x => x.GetUserGroupsByWindowsDeviceUserIds(It.IsAny<IEnumerable<int>>())).Returns(userGroupsLookUp);
        _windowsDeviceLocalUsersService.UpdateLocalUserPassword("userSid", 1);

        _windowsDeviceUserProviderMock.Verify(s => s.ResetPassword(It.IsAny<int>()), Times.Once);
        _windowsDeviceUserProviderMock.Verify(s => s.GetLocalUsersDataByDeviceIdAndSid(It.IsAny<int>(), It.IsAny<string>()), Times.Once);
        _sensitiveDataEncryptionServiceMock.Verify(s => s.Decrypt(It.IsAny<byte[]>(), It.IsAny<DataKey>()), Times.Exactly(1));
    }

    [Test]
    public void GetUserSids_Throws_Exception()
    {
        var validDeviceIds = new[] { 1, 2 };

        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.GetUserSids(null, "validUserName"));
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.GetUserSids(Array.Empty<int>(), "validUserName"));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GetUserSids(validDeviceIds, null));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GetUserSids(validDeviceIds, string.Empty));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GetUserSids(validDeviceIds, " "));
    }

    [Test]
    public void GetUserSids_Success_SingleDevice()
    {
        const string userName = "userName";

        const int deviceId = 11;
        const string userSid = "S-1-2-3-4";
        var sidData = CreateUserSidData(userSid, deviceId);

        _windowsDeviceUserProviderMock.Setup(x => x.GetUserSidByUserNameAndDeviceId(deviceId, userName)).Returns(sidData).Verifiable();

        var result = _windowsDeviceLocalUsersService.GetUserSids([deviceId], userName);

        _windowsDeviceUserProviderMock.Verify(x => x.GetUserSidByUserNameAndDeviceId(deviceId, userName), Times.Once);
        Assert.IsNotNull(result);
        Assert.AreEqual(1, result.Count);
        Assert.IsTrue(result.TryGetValue(deviceId, out var outputSid));
        Assert.AreEqual(userSid, outputSid);
    }

    [Test]
    public void GetUserSids_Success_MultipleDevice()
    {
        const string userName = "userName";

        const int deviceId1 = 11;
        const string userSid1 = "S-1-2-3-4";
        var sidData1 = CreateUserSidData(userSid1, deviceId1);
        const int deviceId2 = 12;
        const string userSid2 = "S-5-6-7-8";
        var sidData2 = CreateUserSidData(userSid2, deviceId2);

        var deviceIds = new[] { deviceId1, deviceId2 };
        var sidsData = new[] { sidData1, sidData2 };
        _windowsDeviceUserProviderMock.Setup(x => x.GetUserSidsByUserNameAndDeviceIds(deviceIds, userName)).Returns(sidsData).Verifiable();

        var result = _windowsDeviceLocalUsersService.GetUserSids(deviceIds, userName);

        _windowsDeviceUserProviderMock.Verify(x => x.GetUserSidsByUserNameAndDeviceIds(deviceIds, userName), Times.Once);
        Assert.IsNotNull(result);
        Assert.AreEqual(2, result.Count);
        Assert.IsTrue(result.TryGetValue(deviceId1, out var outputSid1));
        Assert.AreEqual(userSid1, outputSid1);
        Assert.IsTrue(result.TryGetValue(deviceId2, out var outputSid2));
        Assert.AreEqual(userSid2, outputSid2);
    }

    [Test]
    public void GenerateUsersLog_Throws_Exception()
    {
        var validUsers = new[] { "user1", "user2" };

        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(0, "validDevId", "validAction", validUsers));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, null, "validAction", validUsers));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, string.Empty, "validAction", validUsers));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, " ", "validAction", validUsers));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, "validDevId", null, validUsers));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, "validDevId", string.Empty, validUsers));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, "validDevId", " ", validUsers));
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, "validDevId", "validAction", null));
        Assert.Throws<ArgumentNullException>(() => _windowsDeviceLocalUsersService.GenerateUsersLog(1, "validDevId", "validAction", Array.Empty<string>()));
    }

    [Test]
    public void GenerateUsersLog_Success()
    {
        _eventDispatcherMock.Setup(x => x.DispatchEvent(It.IsAny<IEvent>())).Verifiable();

        _windowsDeviceLocalUsersService.GenerateUsersLog(1, "devId", "action", ["user1", "user2"]);

        _eventDispatcherMock.Verify(x => x.DispatchEvent(It.IsAny<WindowsMultiLocalUsersActionEvent>()), Times.Once);
    }

    [Test]
    public void RenameLocalUser_Throws_Exception()
    {
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.RenameLocalUser(null, "newUsername", 1));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.RenameLocalUser(string.Empty, "newUsername", 1));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.RenameLocalUser(" ", "newUsername", 1));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.RenameLocalUser("userSid", null, 1));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.RenameLocalUser("userSid", string.Empty, 1));
        Assert.Throws<ArgumentException>(() => _windowsDeviceLocalUsersService.RenameLocalUser("userSid", " ", 1));
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.RenameLocalUser("userSid", "newUsername", 0));
    }

    [Test]
    public void RenameLocalUser_Success()
    {
        _windowsDeviceUserProviderMock.Setup(x => x.UpdateUsernameByUserSidAndDeviceId(It.IsAny<string>(), It.IsAny<int>(), It.IsAny<string>())).Verifiable();

        _windowsDeviceLocalUsersService.RenameLocalUser("userSid", "newUsername", 1);

        _windowsDeviceUserProviderMock.Verify(x => x.UpdateUsernameByUserSidAndDeviceId("userSid", 1, "newUsername"), Times.Once);
    }

    [Test]
    public void GetUsernameDataByDeviceIds_ReturnsExpectedGroupedData()
    {
        // Arrange
        var inputDeviceIds = new List<int> { 1, 2 };
        var dummyUsers = new List<WindowsDeviceUserData>
        {
            new() { WindowsDeviceUserId = 101, UserName = "Alice", DeviceId = 1 },
            new() { WindowsDeviceUserId = 102, UserName = "Bob", DeviceId = 1 },
            new() { WindowsDeviceUserId = 103, UserName = "Charlie", DeviceId = 2 }
        };

        _windowsDeviceUserProviderMock
            .Setup(p => p.GetUsernameByDeviceIds(inputDeviceIds))
            .Returns(dummyUsers);

        var result = _windowsDeviceLocalUsersService.GetUsernameDataByDeviceIds(inputDeviceIds);

        Assert.AreEqual(2, result.Count);
        Assert.IsTrue(result.ContainsKey(1));
        Assert.IsTrue(result.ContainsKey(2));

        var usersForDevice1 = result[1].ToList();
        Assert.AreEqual(2, usersForDevice1.Count);
        Assert.AreEqual("Alice", usersForDevice1[0].UserName);
        Assert.AreEqual("Bob", usersForDevice1[1].UserName);

        var usersForDevice2 = result[2].ToList();
        Assert.AreEqual(1, usersForDevice2.Count);
        Assert.AreEqual("Charlie", usersForDevice2[0].UserName);
    }
    [Test]
    public void GetAllTmpLocalUsers_Throws_WhenBatchSizeIsZero()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GetAllTmpLocalUsers(0));
    }

    [Test]
    public void GetAllTmpLocalUsers_Throws_WhenBatchSizeIsNegative()
    {
        Assert.Throws<ArgumentOutOfRangeException>(() => _windowsDeviceLocalUsersService.GetAllTmpLocalUsers(-1));
    }

    [Test]
    public void GetAllTmpLocalUsers_ReturnsAllRecords()
    {
        var testData = new List<WindowsDeviceTmpLocalUserModel>
        {
            new() { WindowsDeviceUserId = 1 },
            new() { WindowsDeviceUserId = 2 },
            new() { WindowsDeviceUserId = 3 }
        };

        _tmpWindowsDeviceUserDataProviderMock
            .Setup(x => x.GetTmpLocalUsersBatch(0, 2))
            .Returns(testData.Take(2).ToList());

        _tmpWindowsDeviceUserDataProviderMock
            .Setup(x => x.GetTmpLocalUsersBatch(2, 2))
            .Returns(testData.Skip(2).ToList());

        var result = _windowsDeviceLocalUsersService.GetAllTmpLocalUsers(2).ToList();

        Assert.AreEqual(3, result.Count);
        Assert.AreEqual(1, result[0].WindowsDeviceUserId);
        Assert.AreEqual(2, result[1].WindowsDeviceUserId);
        Assert.AreEqual(3, result[2].WindowsDeviceUserId);

        _tmpWindowsDeviceUserDataProviderMock.Verify(x => x.GetTmpLocalUsersBatch(0, 2), Times.Once);
        _tmpWindowsDeviceUserDataProviderMock.Verify(x => x.GetTmpLocalUsersBatch(2, 2), Times.Once);
    }

    [Test]
    public void DeleteTmpLocalUsers_CallsProviderWithCorrectIds()
    {
        var testData = new List<WindowsDeviceTmpLocalUserModel>
        {
            new WindowsDeviceTmpLocalUserModel { WindowsDeviceUserId = 1 },
            new WindowsDeviceTmpLocalUserModel { WindowsDeviceUserId = 2 }
        };

        _tmpWindowsDeviceUserDataProviderMock.Setup(x =>
                x.Delete(It.Is<IReadOnlyList<int>>(ids => ids.SequenceEqual(new List<int> { 1, 2 }))))
            .Verifiable();

        _windowsDeviceLocalUsersService.DeleteTmpLocalUsers(testData);

        _tmpWindowsDeviceUserDataProviderMock.Verify(
            x => x.Delete(It.Is<IReadOnlyList<int>>(ids => ids.SequenceEqual(new List<int> { 1, 2 }))),
            Times.Once);
    }

    [Test]
    public void UpdateDecryptedLocalUsers_CallsProviderWithCorrectData()
    {
        var testData = new List<DecryptedLocalUserModel>
        {
            new() { WindowsDeviceUserId = 1, UserName = "User1" },
            new() { WindowsDeviceUserId = 2, UserName = "User2" }
        };

        _windowsDeviceUserProviderMock.Setup(x =>
                x.WindowsDeviceUserNameBulkUpdate(testData))
            .Verifiable();

        _windowsDeviceLocalUsersService.UpdateDecryptedLocalUsers(testData);

        _windowsDeviceUserProviderMock.Verify(x =>
            x.WindowsDeviceUserNameBulkUpdate(testData), Times.Once);
    }

    [Test]
    public void GetDataKeyIdByUserId_ReturnsCorrectMapping()
    {
        var userIds = new List<int> { 1, 2 };
        var expectedResult = new Dictionary<int, int>
        {
            { 1, 101 },
            { 2, 102 }
        };

        _windowsDeviceUserProviderMock.Setup(x =>
                x.GetDataKeyIdsByWindowsDeviceUserIds(userIds))
            .Returns(expectedResult);

        var result = _windowsDeviceLocalUsersService.GetDataKeyIdByUserId(userIds);

        Assert.AreEqual(2, result.Count);
        Assert.AreEqual(101, result[1]);
        Assert.AreEqual(102, result[2]);
    }

    private static IEnumerable<TestCaseData> GetInvalidSid()
    {
        yield return new TestCaseData(null);
        yield return new TestCaseData(string.Empty);
        yield return new TestCaseData(" ");
    }

    private static IEnumerable<TestCaseData> BulkUpdateSuccessData()
    {
        yield return new TestCaseData(new List<WindowsDeviceLocalUserModel>()
        {
            new WindowsDeviceLocalUserModel()
            {
                WindowsDeviceLocalUserId = 0, UserName = "Cal", DeviceId = 1, CreatedDate = DateTime.Now,
                SID = "wewewd", IsMobiControlCreated = true, AutoGeneratedPassword = "12345678",
                UserGroups = new List<string>() { "g1" }
            },
            new WindowsDeviceLocalUserModel()
            {
                WindowsDeviceLocalUserId = 0, UserName = "Hyperion", DeviceId = 2, CreatedDate = DateTime.Now,
                SID = "sdfesrw", IsMobiControlCreated = true, AutoGeneratedPassword = "12345678",
                UserGroups = new List<string>() { "g1" }
            },
        }, 0, 1);

        yield return new TestCaseData(new List<WindowsDeviceLocalUserModel>()
        {
            new WindowsDeviceLocalUserModel()
            {
                WindowsDeviceLocalUserId = 0, UserName = "Cal", DeviceId = 1, CreatedDate = DateTime.Now,
                SID = "wewewd", IsMobiControlCreated = true, AutoGeneratedPassword = "12345678",
                UserGroups = new List<string>() { "g1" }
            }
        }, 1, 0);
    }

    private static DataKey GetDataKey(int dataKeyId)
    {
        return new DataKey
        {
            Id = dataKeyId,
            KeyData = "1234"u8.ToArray(),
            DataKeyAlgorithm = DataKeyAlgorithm.Aes256,
            CreationTime = DateTime.MinValue,
            MasterKeyId = null
        };
    }

    private static WindowsDeviceUserData CreateLocalUserData(int windowsDeviceUserId, string userName, int deviceId, bool isMobiControlCreated, string userSid, int dataKeyId, string password = null)
    {
        return new WindowsDeviceUserData
        {
            WindowsDeviceUserId = windowsDeviceUserId,
            UserName = userName,
            DeviceId = deviceId,
            IsMobiControlCreated = isMobiControlCreated,
            UserSID = userSid,
            AutoGeneratedPassword = password != null ? Encoding.UTF8.GetBytes(password) : null,
            DataKeyId = dataKeyId
        };
    }

    private static WindowsDeviceLocalGroupUserGroupNameData CreateWindowsDeviceUserGroupNameData(int windowsDeviceUserId, int windowsDeviceLocalGroup, string localGroupName)
    {
        return new WindowsDeviceLocalGroupUserGroupNameData
        {
            WindowsDeviceUserId = windowsDeviceUserId,
            WindowsDeviceLocalGroupNameId = windowsDeviceLocalGroup,
            LocalGroupName = localGroupName
        };
    }

    private static WindowsDeviceUserSidData CreateUserSidData(string userSid, int deviceId)
    {
        return new WindowsDeviceUserSidData
        {
            UserSID = userSid,
            DeviceId = deviceId
        };
    }

    private static IReadOnlyList<WindowsDeviceUserData> ToWindowsDeviceData(IReadOnlyList<WindowsDeviceUserTestData> data)
    {
        return data?.Select(x => new WindowsDeviceUserData
        {
            WindowsDeviceUserId = x.WindowsDeviceUserId,
            UserSID = x.UserSID,
            UserName = x.UserName,
            DeviceId = x.DeviceId,
            IsMobiControlCreated = x.IsMobiControlCreated,
            AutoGeneratedPassword = x.AutoGeneratedPassword,
            DataKeyId = x.DataKeyId,
            CreatedDate = x.CreatedDate,
            IsUserLoggedIn = x.IsUserLoggedIn,
            UserDomain = x.UserDomain,
            UserFullName = x.UserFullName,
            WindowsDeviceUserType = x.WindowsDeviceUserType,
            LastCheckInDeviceUserTime = x.LastCheckInDeviceUserTime
        }).ToList();
    }

    private static IEnumerable<WindowsDeviceLocalGroupUserGroupNameData> ToWindowsDeviceGroupNames(IEnumerable<WindowsDeviceUserGroupNameTestData> data)
    {
        return data?.Select(x => new WindowsDeviceLocalGroupUserGroupNameData
        {
            WindowsDeviceUserId = x.WindowsDeviceUserId,
            WindowsDeviceLocalGroupNameId = x.WindowsDeviceLocalGroup,
            LocalGroupName = x.LocalGroupName
        });
    }

    private static ILookup<int, string> GetUserGroupsLookup(IEnumerable<WindowsDeviceLocalGroupUserGroupNameData> userGroupNames)
    {
        return userGroupNames.ToLookup(x => x.WindowsDeviceUserId, x => x.LocalGroupName);
    }

    public class TestData
    {
        public bool SameUser { get; set; }

        public int DeviceId { get; set; }

        public string LocalUserKeysData { get; set; }

        public List<WindowsDeviceUserTestData> LocalUsersFromDb { get; set; }

        public List<WindowsDeviceUserGroupNameTestData> GroupNamesFromDb { get; set; }
    }

    public class WindowsDeviceUserTestData
    {
        public int WindowsDeviceUserId { get; set; }

        public string UserSID { get; set; }

        public string UserName { get; set; }

        public int DeviceId { get; set; }

        public bool IsMobiControlCreated { get; set; }

        public byte[] AutoGeneratedPassword { get; set; }

        public int DataKeyId { get; set; }

        public DateTime? CreatedDate { get; set; }

        public bool IsUserLoggedIn { get; set; }

        public string UserDomain { get; set; }

        public string UserFullName { get; set; }

        public WindowsDeviceUserType WindowsDeviceUserType { get; set; }

        public DateTime? LastCheckInDeviceUserTime { get; set; }
    }

    public class WindowsDeviceUserGroupNameTestData
    {
        public int WindowsDeviceUserId { get; set; }

        public int WindowsDeviceLocalGroup { get; set; }

        public string LocalGroupName { get; set; }
    }
}
