using Soti.MobiControl.Events;
using Soti.MobiControl.Events.EventOriginators;
using Soti.MobiControl.Events.ModelInterfaces;

namespace Soti.MobiControl.WindowsModern.Web.Implementation.Events
{
    [EventMetadata(
        "ViewedLocalUserAutoGeneratedPassword", "Requested to view the Local User Auto-generated Password", "Auto-generated password accessed for local user \"{0}\" by \"{1}\".", AlertManagerType.Device)]
    internal sealed class ViewedLocalUserAutoGeneratedPasswordEvent : UserOriginatedEvent, IDeviceBoundEvent, IParameterizedEvent
    {
        internal ViewedLocalUserAutoGeneratedPasswordEvent(int userPrincipalId, string userName, int deviceId, string devId, string localUserName)
            : base(userPrincipalId, userName, EventSeverity.Information)
        {
            EventAdditionalParameters = new[] { localUserName, userName };
            DeviceId = deviceId;
            DevId = devId;
        }

        public string[] EventAdditionalParameters { get; }

        public int DeviceId { get; }

        public string DevId { get; }
    }
}
