using System;
using NUnit.Framework;
using Soti.MobiControl.Events;
using Soti.MobiControl.WindowsModern.Web.Implementation.Events;

namespace Soti.MobiControl.WindowsModern.Implementation.Tests.Events
{
    internal class ViewedLocalUserAutoGeneratedPasswordTests
    {
        [Test]
        public void ViewedAutoGeneratedPassword_Test()
        {
            const int userPrincipalId = 1;
            const string userName = "userName1";
            const int deviceId = 100001;
            var devId = Guid.NewGuid().ToString();
            const string localUserName = "UserName2";
            var testEvent = new ViewedLocalUserAutoGeneratedPasswordEvent(userPrincipalId, userName, deviceId, devId, localUserName);
            Assert.That(testEvent.EventSeverity, Is.EqualTo(EventSeverity.Information));
            Assert.That(testEvent.DeviceId, Is.EqualTo(deviceId));
            Assert.That(testEvent.DevId, Is.EqualTo(devId));
            Assert.That(testEvent.EventAdditionalParameters[0], Is.EqualTo(localUserName));
        }
    }
}
