using System;
using System.Collections.Generic;
using Soti.MobiControl.WindowsModern.Models.Enums;

namespace Soti.MobiControl.WindowsModern.Implementation.Models;

public sealed class WindowsDeviceUserData
{
    /// <summary>
    /// Gets or sets the ID of the Windows device user.
    /// </summary>
    public int WindowsDeviceUserId { get; set; }

    /// <summary>
    /// Gets or sets SID of the user.
    /// </summary>
    public string UserSID { get; set; }

    /// <summary>
    /// Gets or sets username of the user.
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// Gets or sets UserGroups.
    /// </summary>
    public IEnumerable<string> UserGroups { get; set; }

    /// <summary>
    /// Gets or sets ID of the device.
    /// </summary>
    public int DeviceId { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the user was created through MobiControl.
    /// </summary>
    public bool IsMobiControlCreated { get; set; }

    /// <summary>
    /// Gets or sets Local User Auto Generated Password.
    /// </summary>
    public byte[] AutoGeneratedPassword { get; set; }

    /// <summary>
    /// Gets or sets the DataKeyId.
    /// </summary>
    public int DataKeyId { get; set; }

    /// <summary>
    /// Gets or sets the date the user was created.
    /// </summary>
    public DateTime? CreatedDate { get; set; }

    /// <summary>
    /// Gets or sets IsUserLoggedIn defining if the user is logged in.
    /// Table default value: false.
    /// </summary>
    public bool IsUserLoggedIn { get; set; }

    /// <summary>
    /// Gets or sets the domain of the user, if the user type is 1 - Domain.
    /// </summary>
    public string UserDomain { get; set; }

    /// <summary>
    /// Gets or sets the full name of the user.
    /// </summary>
    public string UserFullName { get; set; }

    /// <summary>
    /// Gets or sets the WindowsDeviceUserType. It can be 0 - Local or 1 - Domain.
    /// </summary>
    public WindowsDeviceUserType WindowsDeviceUserType { get; set; }

    /// <summary>
    /// Gets or sets the time at which the logged-in user information was last updated.
    /// </summary>
    public DateTime? LastCheckInDeviceUserTime { get; set; }
}
